name: Guilt Free Life
favicon: null
layout_spectrum: 1
typography_spectrum: 0.548003823729232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0811'
    - '#3f4f4e'
    - '#3ca8e8'
    - '#63776e'
    - '#b9c3b4'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0.337022882187739
purpose: []
